version: "3.9"


services:

#  security:
#    image: seanhorner/utopia-backend-microservice-security
#    ports:
#      - "5080:5000"
#    links:
#      - "db:database"

  flights:
    image: seanhorner/utopia-backend-microservice-flights
    ports:
      - "5081:5000"
    links:
      # - "security:sec"
      - "db:database"

  users:
    image: seanhorner/utopia-backend-microservice-users
    ports:
      - "5082:5000"
    links:
      # - "security:sec"
      - "db:database"

  bookings:
    image: seanhorner/utopia-backend-microservice-bookings
    ports:
      - "5083:5000"
    links:
      # - "security:sec"
      - "db:database"

  data_loading:
    image: seanhorner/utopia-backend-microservice-data_loading
    ports:
      - "5084:5000"
    links:
      # - "security:sec"
      - "db:database"
    depends_on:
      - users
      - flights
      - bookings

  db:
    image: seanhorner/utopia-backend-database
    ports:
      - "33066:3306"