
version: "3.9"

services:
  security:
    image: seanhorner/utopia_microservice_security
    secrets:
      - utopia_rds_pswd
      - utopia_rds_inst
      - utopia_secret_key

  flights:
    image: seanhorner/utopia_microservice_flights
    environment:
      - RDS_PSWD=/run/secrets/utopia_rds_pswd
      - RDS_INST=/run/secrets/utopia_rds_inst
      - SECRET_KEY=/run/secrets/utopia_secret_key
    secrets:
      - utopia_rds_pswd
      - utopia_rds_inst
      - utopia_secret_key
    entrypoint: /app/entry_script.sh

  users:
    image: seanhorner/utopia_microservice_users
    environment:
      - RDS_PSWD=/run/secrets/utopia_rds_pswd
      - RDS_INST=/run/secrets/utopia_rds_inst
      - SECRET_KEY=/run/secrets/utopia_secret_key
    secrets:
      - utopia_rds_pswd
      - utopia_rds_inst
      - utopia_secret_key

  bookings:
    image: seanhorner/utopia_microservice_bookings
    environment:
      - RDS_PSWD=/run/secrets/utopia_rds_pswd
      - RDS_INST=/run/secrets/utopia_rds_inst
      - SECRET_KEY=/run/secrets/utopia_secret_key
    secrets:
      - utopia_rds_pswd
      - utopia_rds_inst
      - utopia_secret_key

  data_loader:
    image: seanhorner/utopia_microservice_data_loader
    environment:
      - RDS_PSWD=/run/secrets/utopia_rds_pswd
      - RDS_INST=/run/secrets/utopia_rds_inst
      - SECRET_KEY=/run/secrets/utopia_secret_key
    secrets:
      - utopia_rds_pswd
      - utopia_rds_inst
      - utopia_secret_key
    depends_on:
      - users
      - flights
      - bookings

secrets:
  utopia_rds_pswd:
    file: utopia_rds_pswd
  utopia_rds_inst:
    file: utopia_rds_inst
  utopia_secret_key:
    file: utopia_secret_key