version: "3"

services:

  security:
    image: utopia_backend_security_microservice-sh
    build: ../backend/microservice_security
    secrets:
      - utopia_db_uri
      - utopia_secret_key
    ports:
      - "5090:5000"

  bookings:
    image: utopia_backend_bookings_microservice-sh
    build: ../backend/microservice_bookings
    secrets:
      - utopia_db_uri
      - utopia_secret_key
    ports:
      - "5010:5000"

  flights:
    image: utopia_backend_flights_microservice-sh
    build: ../backend/microservice_flights
    secrets:
      - utopia_db_uri
      - utopia_secret_key
    ports:
      - "5020:5000"

  users:
    image: utopia_backend_users_microservice-sh
    build: ../backend/microservice_users
    secrets:
      - utopia_db_uri
      - utopia_secret_key
    ports:
      - "5030:5000"

  data_prod:
    image: utopia_backend_data_producers_microservice-sh
    build: ../backend/microservice_data_producers
    secrets:
      - utopia_db_uri
      - utopia_secret_key
    depends_on:
      - users
      - flights
      - bookings
    ports:
      - "5050:5000"

  admin:
    image: utopia_frontend_admin_microservice-sh
    build: ../frontend/microservice_admin
    secrets:
      - utopia_secret_key
    ports:
      - "5000:5000"
    depends_on:
      - users
      - flights
      - bookings

secrets:
  utopia_db_uri:
    file: utopia_db_uri
  utopia_secret_key:
    file: utopia_secret_key
